@To-Dos_App.API_HostAddress = https://localhost:7151
@To_Dos_App.API_HostAddress = http://localhost:5278



GET {{To-Dos_App.API_HostAddress}}/api/todotask

###

GET {{To-Dos_App.API_HostAddress}}/api/todotask/containing?substring=perra

###

PUT {{To-Dos_App.API_HostAddress}}/api/todotask/mark/08dc3f17-3185-4922-81ac-0ade4a00df94
Content-Type: application/json

{
  //Guid
}

###



###
